### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by andrei-a-papou** [Tiefkuehlpizze/OABXDecrypt#2]
Is it possible to add build instructions? 

I've cloned the git repo, ran `mvn install` and it does build the jar file under ./target.

However, when I run the jar, I get an error:

```
java -jar OABXDecrypt-1.0.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: org/tinylog/Logger
	at tkp.App.main(App.java:10)
Caused by: java.lang.ClassNotFoundException: org.tinylog.Logger
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

The jar file is small, much smaller than the one downloadable under Releases.

This is under Debian 11.3.

**Comment by Tiefkuehlpizze** [comment]
Hi,
thanks for your interest. To build the fat jar, you can run `mvn package assembly:single`. I'll add it to the readme and update it with some hints from your other issues. Maybe, I'm going to invest some time to do something about them.

**Comment by andrei-a-papou** [comment]
Thanks, the fat jar instructions work!

If you can find some time to make the code work with v7.0.0, it would be much appreciated. 

Unfortunately, I've no Java or Kotlin experience, but I'll certainly help with testing.

**Comment by Tiefkuehlpizze** [comment]
Thanks for the feedback! It's shouldn't be too much. I just have to think about a good way how to solve the problem. I have absolutely no clue, who's using this tool and why they need it. From my perspective it's a tinker tool for a very special interest since you can always create an unencrypted backup so you wouldn't need this tool at all. :)

**Comment by andrei-a-papou** [comment]
> who's using this tool and why they need it

I think the ability to decrypt backups on a PC even the phone is lost could be a life-saver in some situations. It provides a good contingency plan/plan B in case there are issues with NeoBackup's backwards compatibility, availability, bugs, etc. 

It's just a good idea to have another option on a PC -- this way you are not locked into using NeoBackup.

Also, in some cases I might not even want to restore the backup to Android. Say, I might need to just extract my Skype or Viber messages from the apps' DBs for archival. I could do that from a backup, without having to restore anything on the device.

> create an unencrypted backup
Sometimes it's not an option, depending on the sensitivity of user data. SeedVault, for example, doesn't allow unencrypted backups at all. In NeoBackup, I would default to encrypted backups and print a fat warning when things are unencrypted :)

I think the demand for such tools is there:
1. NeoBackup has a FAQ entry on this topic, meaning people keep asking this question often enough :)
2. SeedVault is more limited than NeoBackup, but does include a tool to decrypt and/or re-encrypt the backups. It was requested by users.


> From my perspective it's a tinker tool

Hey, all it needs IMO is a more secure password input option (secure readline? file input?) and to support v7.0.0! It would be an awesome tool then :)
